### ISSUE TITLE
Domain generation failed

### ISSUE THREAD

**Issue by cdalexndr** [etiennestuder/gradle-jooq-plugin#169]
Plugin version 5.2.1, jooq 3.14.8
Worked with plugin version 5.0.1, jooq 3.13.4

With:
```
forcedType {
    userType = 'mypackage.Country'
    binding = 'mypackage.CountryDbType'
    includeTypes = '.*'
    includeExpression = '.*\\.COUNTRY.*'
}
```
`CountryDbType` extends `org.jooq.Binding<String, Country>`

Generation fails:
Domains.java:
```
    public static final Domain<Country> COUNTRY = Internal.createDomain(
          schema()
        , DSL.name("country")
        , SQLDataType.VARCHAR(2)
        , Internal.createCheck(null, null, "CHECK ((length((VALUE)::text) = 2))")
    );
```
```
 error: incompatible types: inference variable T has incompatible equality constraints Country,String
    public static final Domain<Country> COUNTRY = Internal.createDomain(
                                                                       ^
  where T is a type-variable:
    T extends Object declared in method <T>createDomain(Schema,Name,DataType<T>,Check<?>...)
```

Domain usage:
`public final TableField<CategoryRecord, Country> COUNTRY = createField(DSL.name("country"), jooq.Domains.COUNTRY.getDataType(), this, "", new CountryDbType());`
```
 error: no suitable method found for createField(Name,DataType<Country>,Category,String,CountryDbType)
    public final TableField<CategoryRecord, Country> COUNTRY = createField(DSL.name("country"), jooq.Domains.COUNTRY.getDataType(), this, "", new CountryDbType());
                                                               ^
    method AbstractTable.<R#1,T#1>createField(String,DataType<T#1>,Table<R#1>) is not applicable
      (cannot infer type-variable(s) R#1,T#1
        (actual and formal argument lists differ in length))
    method AbstractTable.<R#2,T#2>createField(String,DataType<T#2>,Table<R#2>,String) is not applicable
      (cannot infer type-variable(s) R#2,T#2
        (actual and formal argument lists differ in length))
    method AbstractTable.<R#3,T#3,U#1>createField(String,DataType<T#3>,Table<R#3>,String,Converter<T#3,U#1>) is not applicable
      (cannot infer type-variable(s) R#3,T#3,U#1
        (argument mismatch; Name cannot be converted to String))
    method AbstractTable.<R#4,T#4,U#2>createField(String,DataType<T#4>,Table<R#4>,String,Binding<T#4,U#2>) is not applicable
      (cannot infer type-variable(s) R#4,T#4,U#2
        (argument mismatch; Name cannot be converted to String))
    method AbstractTable.<R#5,T#5,X#1,U#3>createField(String,DataType<T#5>,Table<R#5>,String,Converter<X#1,U#3>,Binding<T#5,X#1>) is not applicable
      (cannot infer type-variable(s) R#5,T#5,X#1,U#3
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#6>createField(String,DataType<T#6>) is not applicable
      (cannot infer type-variable(s) T#6
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#7>createField(String,DataType<T#7>,String) is not applicable
      (cannot infer type-variable(s) T#7
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#8,U#4>createField(String,DataType<T#8>,String,Converter<T#8,U#4>) is not applicable
      (cannot infer type-variable(s) T#8,U#4
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#9,U#5>createField(String,DataType<T#9>,String,Binding<T#9,U#5>) is not applicable
      (cannot infer type-variable(s) T#9,U#5
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#10,X#2,U#6>createField(String,DataType<T#10>,String,Converter<X#2,U#6>,Binding<T#10,X#2>) is not applicable
      (cannot infer type-variable(s) T#10,X#2,U#6
        (argument mismatch; Name cannot be converted to String))
    method AbstractTable.<R#7,T#11>createField(Name,DataType<T#11>,Table<R#7>) is not applicable
      (cannot infer type-variable(s) R#7,T#11
        (actual and formal argument lists differ in length))
    method AbstractTable.<R#8,T#12>createField(Name,DataType<T#12>,Table<R#8>,String) is not applicable
      (cannot infer type-variable(s) R#8,T#12
        (actual and formal argument lists differ in length))
    method AbstractTable.<R#9,T#13,U#7>createField(Name,DataType<T#13>,Table<R#9>,String,Converter<T#13,U#7>) is not applicable
      (cannot infer type-variable(s) R#9,T#13,U#7
        (argument mismatch; CountryDbType cannot be converted to Converter<T#13,U#7>))
    method AbstractTable.<R#10,T#14,U#8>createField(Name,DataType<T#14>,Table<R#10>,String,Binding<T#14,U#8>) is not applicable
      (inference variable T#14 has incompatible equality constraints String,Country)
    method AbstractTable.<R#11,T#15,X#3,U#9>createField(Name,DataType<T#15>,Table<R#11>,String,Converter<X#3,U#9>,Binding<T#15,X#3>) is not applicable
      (cannot infer type-variable(s) R#11,T#15,X#3,U#9
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#16>createField(Name,DataType<T#16>) is not applicable
      (cannot infer type-variable(s) T#16
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#17>createField(Name,DataType<T#17>,String) is not applicable
      (cannot infer type-variable(s) T#17
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#18,U#10>createField(Name,DataType<T#18>,String,Converter<T#18,U#10>) is not applicable
      (cannot infer type-variable(s) T#18,U#10
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#19,U#11>createField(Name,DataType<T#19>,String,Binding<T#19,U#11>) is not applicable
      (cannot infer type-variable(s) T#19,U#11
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#20,X#4,U#12>createField(Name,DataType<T#20>,String,Converter<X#4,U#12>,Binding<T#20,X#4>) is not applicable
      (cannot infer type-variable(s) T#20,X#4,U#12
        (argument mismatch; Category cannot be converted to String))
  where R#1,T#1,R#2,T#2,R#3,T#3,U#1,R#4,T#4,U#2,R#5,T#5,X#1,U#3,T#6,R#6,T#7,T#8,U#4,T#9,U#5,T#10,X#2,U#6,R#7,T#11,R#8,T#12,R#9,T#13,U#7,R#10,T#14,U#8,R#11,T#15,X#3,U#9,T#16,T#17,T#18,U#10,T#19,U#11,T#20,X#4,U#12 are type-variables:
    R#1 extends Record declared in method <R#1,T#1>createField(String,DataType<T#1>,Table<R#1>)
    T#1 extends Object declared in method <R#1,T#1>createField(String,DataType<T#1>,Table<R#1>)
    R#2 extends Record declared in method <R#2,T#2>createField(String,DataType<T#2>,Table<R#2>,String)
    T#2 extends Object declared in method <R#2,T#2>createField(String,DataType<T#2>,Table<R#2>,String)
    R#3 extends Record declared in method <R#3,T#3,U#1>createField(String,DataType<T#3>,Table<R#3>,String,Converter<T#3,U#1>)
    T#3 extends Object declared in method <R#3,T#3,U#1>createField(String,DataType<T#3>,Table<R#3>,String,Converter<T#3,U#1>)
    U#1 extends Object declared in method <R#3,T#3,U#1>createField(String,DataType<T#3>,Table<R#3>,String,Converter<T#3,U#1>)
    R#4 extends Record declared in method <R#4,T#4,U#2>createField(String,DataType<T#4>,Table<R#4>,String,Binding<T#4,U#2>)
    T#4 extends Object declared in method <R#4,T#4,U#2>createField(String,DataType<T#4>,Table<R#4>,String,Binding<T#4,U#2>)
    U#2 extends Object declared in method <R#4,T#4,U#2>createField(String,DataType<T#4>,Table<R#4>,String,Binding<T#4,U#2>)
    R#5 extends Record declared in method <R#5,T#5,X#1,U#3>createField(String,DataType<T#5>,Table<R#5>,String,Converter<X#1,U#3>,Binding<T#5,X#1>)
    T#5 extends Object declared in method <R#5,T#5,X#1,U#3>createField(String,DataType<T#5>,Table<R#5>,String,Converter<X#1,U#3>,Binding<T#5,X#1>)
    X#1 extends Object declared in method <R#5,T#5,X#1,U#3>createField(String,DataType<T#5>,Table<R#5>,String,Converter<X#1,U#3>,Binding<T#5,X#1>)
    U#3 extends Object declared in method <R#5,T#5,X#1,U#3>createField(String,DataType<T#5>,Table<R#5>,String,Converter<X#1,U#3>,Binding<T#5,X#1>)
    T#6 extends Object declared in method <T#6>createField(String,DataType<T#6>)
    R#6 extends Record declared in class AbstractTable
    T#7 extends Object declared in method <T#7>createField(String,DataType<T#7>,String)
    T#8 extends Object declared in method <T#8,U#4>createField(String,DataType<T#8>,String,Converter<T#8,U#4>)
    U#4 extends Object declared in method <T#8,U#4>createField(String,DataType<T#8>,String,Converter<T#8,U#4>)
    T#9 extends Object declared in method <T#9,U#5>createField(String,DataType<T#9>,String,Binding<T#9,U#5>)
    U#5 extends Object declared in method <T#9,U#5>createField(String,DataType<T#9>,String,Binding<T#9,U#5>)
    T#10 extends Object declared in method <T#10,X#2,U#6>createField(String,DataType<T#10>,String,Converter<X#2,U#6>,Binding<T#10,X#2>)
    X#2 extends Object declared in method <T#10,X#2,U#6>createField(String,DataType<T#10>,String,Converter<X#2,U#6>,Binding<T#10,X#2>)
    U#6 extends Object declared in method <T#10,X#2,U#6>createField(String,DataType<T#10>,String,Converter<X#2,U#6>,Binding<T#10,X#2>)
    R#7 extends Record declared in method <R#7,T#11>createField(Name,DataType<T#11>,Table<R#7>)
    T#11 extends Object declared in method <R#7,T#11>createField(Name,DataType<T#11>,Table<R#7>)
    R#8 extends Record declared in method <R#8,T#12>createField(Name,DataType<T#12>,Table<R#8>,String)
    T#12 extends Object declared in method <R#8,T#12>createField(Name,DataType<T#12>,Table<R#8>,String)
    R#9 extends Record declared in method <R#9,T#13,U#7>createField(Name,DataType<T#13>,Table<R#9>,String,Converter<T#13,U#7>)
    T#13 extends Object declared in method <R#9,T#13,U#7>createField(Name,DataType<T#13>,Table<R#9>,String,Converter<T#13,U#7>)
    U#7 extends Object declared in method <R#9,T#13,U#7>createField(Name,DataType<T#13>,Table<R#9>,String,Converter<T#13,U#7>)
    R#10 extends Record declared in method <R#10,T#14,U#8>createField(Name,DataType<T#14>,Table<R#10>,String,Binding<T#14,U#8>)
    T#14 extends Object declared in method <R#10,T#14,U#8>createField(Name,DataType<T#14>,Table<R#10>,String,Binding<T#14,U#8>)
    U#8 extends Object declared in method <R#10,T#14,U#8>createField(Name,DataType<T#14>,Table<R#10>,String,Binding<T#14,U#8>)
    R#11 extends Record declared in method <R#11,T#15,X#3,U#9>createField(Name,DataType<T#15>,Table<R#11>,String,Converter<X#3,U#9>,Binding<T#15,X#3>)
    T#15 extends Object declared in method <R#11,T#15,X#3,U#9>createField(Name,DataType<T#15>,Table<R#11>,String,Converter<X#3,U#9>,Binding<T#15,X#3>)
    X#3 extends Object declared in method <R#11,T#15,X#3,U#9>createField(Name,DataType<T#15>,Table<R#11>,String,Converter<X#3,U#9>,Binding<T#15,X#3>)
    U#9 extends Object declared in method <R#11,T#15,X#3,U#9>createField(Name,DataType<T#15>,Table<R#11>,String,Converter<X#3,U#9>,Binding<T#15,X#3>)
    T#16 extends Object declared in method <T#16>createField(Name,DataType<T#16>)
    T#17 extends Object declared in method <T#17>createField(Name,DataType<T#17>,String)
    T#18 extends Object declared in method <T#18,U#10>createField(Name,DataType<T#18>,String,Converter<T#18,U#10>)
    U#10 extends Object declared in method <T#18,U#10>createField(Name,DataType<T#18>,String,Converter<T#18,U#10>)
    T#19 extends Object declared in method <T#19,U#11>createField(Name,DataType<T#19>,String,Binding<T#19,U#11>)
    U#11 extends Object declared in method <T#19,U#11>createField(Name,DataType<T#19>,String,Binding<T#19,U#11>)
    T#20 extends Object declared in method <T#20,X#4,U#12>createField(Name,DataType<T#20>,String,Converter<X#4,U#12>,Binding<T#20,X#4>)
    X#4 extends Object declared in method <T#20,X#4,U#12>createField(Name,DataType<T#20>,String,Converter<X#4,U#12>,Binding<T#20,X#4>)
    U#12 extends Object declared in method <T#20,X#4,U#12>createField(Name,DataType<T#20>,String,Converter<X#4,U#12>,Binding<T#20,X#4>)
```

**Comment by cdalexndr** [comment]
It seems that changing `includeTypes` from `'.*'` to `'country'` (matches the db domain name), fixes this issue.

**Comment by etiennestuder** [comment]
This is something related to jooq and not the gradle-jooq-plugin. @lukaseder would be able to best comment on it, though you have resolved it yourself by now.
