### ISSUE TITLE
Updating the gradle-jooq-plugin from 8.2.3 to 9.0 breaks the code generation

### ISSUE THREAD

**Issue by bugaandreea** [etiennestuder/gradle-jooq-plugin#676]
Updating gradle-jooq-plugin from version 8.2.3 to version 9.0 results in the following error when trying to generate the jooq classes from the database:
```
09:33:46 WARNING org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 127; cvc-elt.1.a: Cannot find the declaration of element 'configuration'.
cvc-elt.1.a: Cannot find the declaration of element 'configuration'.

Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String org.jooq.meta.jaxb.Generator.getJava()'
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:396)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:246)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:241)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:213)
```

Main part of the build.gradle.kts file:
```
import org.gradle.configurationcache.extensions.capitalized
import org.jooq.meta.jaxb.ForcedType
import org.jooq.meta.jaxb.Logging
import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

buildscript {
  repositories {
	.....
    mavenCentral()
  }
}

repositories {
  .....
  mavenCentral()
}

plugins {
  java
  jacoco
  id("org.springframework.boot") version "3.2.1"
  id("io.spring.dependency-management") version "1.1.4"
  id("com.patdouble.awsecr") version "0.7.0"
  id("com.bmuschko.docker-spring-boot-application") version "9.4.0"
  id("nu.studer.jooq") version "9.0"
  id("org.sonarqube") version "4.4.1.3373"
  // generates git.properties for exposing via /actuator/info
  id("com.gorylenko.gradle-git-properties") version "2.4.1"
  id("org.openapi.generator") version "7.2.0"
  id("com.diffplug.spotless") version "6.23.3"
}

java {
  sourceCompatibility = JavaVersion.VERSION_17
  targetCompatibility = JavaVersion.VERSION_17
}

val awsSdkVersion = "1.12.629"
val springRetryVersion = "2.0.5"
val springCloudVersion = "2023.0.0"
val openApiVersion = "2.3.0"
val testContainersVersion = "1.19.3"
val jooqVersion = "3.19.1"

dependencyManagement {
  imports {
    mavenBom("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")
  }
}

dependencies {
  implementation("org.springframework.boot:spring-boot-starter-web")
  implementation("org.springframework.boot:spring-boot-starter-security")
  implementation("org.springframework.boot:spring-boot-starter-actuator")
  implementation("org.springframework.boot:spring-boot-starter-jdbc")
  implementation("org.springframework.boot:spring-boot-starter-validation")
  implementation("org.springframework.boot:spring-boot-starter-cache")
  implementation("org.springframework.cloud:spring-cloud-starter-openfeign")
  implementation("org.springframework.retry:spring-retry:${springRetryVersion}")
  implementation("com.github.ben-manes.caffeine:caffeine:3.1.8")

  annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")

  implementation("com.amazonaws:aws-java-sdk-iam:${awsSdkVersion}")
  implementation("com.amazonaws:aws-java-sdk-rds:${awsSdkVersion}")

  implementation("org.postgresql:postgresql:42.7.1") {
    exclude(group = "org.slf4j", module = "slf4j-simple")
  }
  implementation("org.flywaydb:flyway-core")
  implementation("org.jooq:jooq:${jooqVersion}")
  implementation("org.jooq:jooq-meta:${jooqVersion}")
  implementation("org.jooq:jooq-codegen:${jooqVersion}")
  jooqGenerator("org.postgresql:postgresql:42.7.1")

  implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.16.1")
  implementation("com.fasterxml.jackson.core:jackson-core:2.16.1")


  implementation("org.eclipse.jgit:org.eclipse.jgit:6.8.0.202311291450-r")
  implementation("com.slack.api:slack-api-client:1.36.1")

  implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:${openApiVersion}")
  // additional feign dependencies required by generated code
  implementation("io.github.openfeign:feign-okhttp")
  implementation("io.github.openfeign:feign-jackson")
  implementation("org.openapitools:jackson-databind-nullable:0.2.6")

  testImplementation("org.springframework.boot:spring-boot-starter-test")
  testImplementation("org.testcontainers:postgresql:${testContainersVersion}")
  testImplementation("org.testcontainers:junit-jupiter:${testContainersVersion}")
  testImplementation("org.eclipse.jgit:org.eclipse.jgit.junit:6.8.0.202311291450-r")
  testImplementation("com.amazonaws:aws-java-sdk-ssm:${awsSdkVersion}")
  testImplementation("com.google.guava:guava-testlib:33.0.0-jre")
}

// region JooQ DB Classes Generation
jooq {
  version.set("3.19.1")  // the default (can be omitted)
  edition.set(nu.studer.gradle.jooq.JooqEdition.OSS)  // the default (can be omitted)
  configurations {
    create("main") {
      generateSchemaSourceOnCompilation.set(false)

      jooqConfiguration.apply {
        logging = Logging.WARN
        jdbc.apply {
          driver = "org.postgresql.Driver"
		  ........

        }
        generator.apply {
          name = "org.jooq.codegen.DefaultGenerator"
          database.apply {
            name = "org.jooq.meta.postgres.PostgresDatabase"
            inputSchema = "public"
            excludes = "flyway_schema_history"

          }
          generate.apply {
            isDeprecated = false
            isRecords = true
            isImmutablePojos = true
            isFluentSetters = true
          }
          target.apply {
            .....
          }
          strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
        }
      }
    }
  }
}
//endregion
```

The jooq version used is 3.19.1 and gradle version of the project is 8.5.
![image](https://github.com/etiennestuder/gradle-jooq-plugin/assets/6025874/cbb078c6-b3a6-4a48-9e75-095fbaeede81)

**Comment by vertti** [comment]
From our working build with version 8.2.1, both upgrade to 9 and upgrade to 8.2.3 breaks the build with

```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String org.jooq.meta.jaxb.Generator.getJava()'
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:396)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:246)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:241)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:213)
```

**Comment by evaldasu** [comment]
I am having the same issue. 8.2.3 works just fine, but 9.0 fails with the message `cvc-elt.1.a: Cannot find the declaration of element 'configuration'`.

I have a sense it's related to this statement in [Migrating from jOOQ plugin 8.x to 9.x](https://github.com/etiennestuder/gradle-jooq-plugin/tree/main#migrating-from-jooq-plugin-8x-to-9x): 

> Declare any additional jOOQ dependencies with their specific versions, since the jOOQ plugin no longer registers any custom dependency resolution rules

I've compared `gradle dependencies` output between using 8.2.3 and 9.0 and there are some differences:
8.2.3:
![image](https://github.com/etiennestuder/gradle-jooq-plugin/assets/107461273/5d8daa89-ca32-4b78-a34d-08158814b1bc)

9.0:
![image](https://github.com/etiennestuder/gradle-jooq-plugin/assets/107461273/7379df6a-b877-4684-928a-a0e340a63c99)

**Comment by etiennestuder** [comment]
Thanks, @evaldasu. 

If you see a downgrade of the jOOQ versions from 3.19.1 to 3.18.7 in Gradle's dependencies report, the downgrade is likely due to the application of the Spring Boot Gradle plugin enforcing what version of jOOQ should be used. The gradle-jooq-plugin in version 9.0 definitely applies version 3.19.1.
