### ISSUE TITLE
jOOQ 3.11.0 support

### ISSUE THREAD

**Issue by ben-manes** [etiennestuder/gradle-jooq-plugin#71]
```gradle
Caused by: java.lang.NoClassDefFoundError: org/jooq/util/jaxb/Configuration
        at nu.studer.gradle.jooq.JooqExtension.findOrCreateConfig(JooqExtension.groovy:79)
```

The jaxb classes were moved to [org.jooq.meta.jaxb](https://github.com/jOOQ/jOOQ/tree/version-3.11.0/jOOQ-meta/src/main/java/org/jooq/meta/jaxb) during jigsaw modularization. This error prevents upgrading, unfortunately, making it a blocking issue.

cc @lukaseder

**Comment by lukaseder** [comment]
Thanks a lot for the quick feedback. My oversight - I hadn't thought of this dependency. Indeed, the packages were renamed to avoid having the same package name (`org.jooq.util`) in different modules. A necessary prerequisite for the modularisation which should take place in jOOQ 3.12.

All the classes are the same, the only difference is `s/util/meta` in jOOQ-meta and `s/util/codegen` in jOOQ-codegen.

The relevant change (with a more detailed description) is here:
https://github.com/jOOQ/jOOQ/issues/7419

**Comment by lukaseder** [comment]
... of course, the most thorough solution would be to publish this plugin using the same version scheme as jOOQ's main version schemes. This way, there would be always a version that's in sync with jOOQ.

We've discussed this before - I forgot why the idea was abandoned.

**Comment by gwojciechowski** [comment]
I have one more question.
I use 'gradle-jooq-plugin' + https://github.com/wstrzalka/gradle-flyway-jooq-plugin

After migrate to 3.11.0 version my spring build generate this problem:

`> Task :generateClosecrossJooqSchemaSource FAILED
Error: Could not find or load main class org.jooq.util.GenerationTool`

Do you have any ideas? Thanks a lot

`jooq {
    version = "${jooqVersion}"
    edition = 'OSS'
    closecross(sourceSets.main) {
        jdbc {
            driver = props['spring.datasource.driver']
            url = props['spring.datasource.url']
            user = props['spring.datasource.username']
            password = props['spring.datasource.password']
        }
        generator {
            name = 'org.jooq.util.DefaultGenerator'
            strategy {
                name = 'org.jooq.util.DefaultGeneratorStrategy'
            }

            database {
                name = 'org.jooq.util.postgres.PostgresDatabase'
                schemata {
                    schema {
                        inputSchema = jooqProjectSchema
                    }
                }
            }
            generate {
                relations = true
                deprecated = false
                records = true
                immutablePojos = true
                fluentSetters = true
            }
            target {
                packageName = appName
            }
        }
    }
}
`

**Comment by lukaseder** [comment]
This is the same problem, different affected class.

**Comment by ahamana** [comment]
@lukaseder Can't we use this plugin with jOOQ 3.11.x until jOOQ 3.12?

**Comment by lukaseder** [comment]
@ahamana Why not? jOOQ 3.11 was released a few days ago, and this plugin is not yet up to date. There will be a fix...

**Comment by ahamana** [comment]
@lukaseder I see, thanks!

**Comment by masc3d** [comment]
meanwhile you could use `com.github.masc3d:gradle-jooq-plugin:master-SNAPSHOT` as a temporary workaround

**Comment by etiennestuder** [comment]
I'm offsite this week, but will fix this issue early next week.

**Comment by stangls** [comment]
Note that also the strategy changed from `org.jooq.util.DefaultGeneratorStrategy` to `org.jooq.codegen.DefaultGeneratorStrategy`
and the database-support changed from `org.jooq.util.xxx.XxxDatabase` to `org.jooq.meta.xxx.XxxDatabase`

**Comment by ben-manes** [comment]
@etiennestuder please remember to take of this soonish. thanks!

**Comment by stangls** [comment]
Jooq seems to introduce a bunch of great features but also breaking changes for the users (not only the plugin writers).
But nevertheless it will still be a good experience if this plugin will adapt.
Thank you @etiennestuder for your efforts on this one.

**Comment by etiennestuder** [comment]
> @etiennestuder please remember to take care of this soonish. thanks!

@ben-manes Yes, I will take care of it this week-end.

**Comment by etiennestuder** [comment]
I've released v3.0.0 which is compatible with jOOQ 3.11.x. When using a version of jOOQ 3.10.x or older, one has to continue to use v2.0.11.

**Comment by ben-manes** [comment]
Unfortunately I get the following error ([buildscan](https://scans.gradle.com/s/d7vi3drsnc7nk/)):

```
> Task :generateLoaddocsJooqSchemaSource FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateLoaddocsJooqSchemaSource'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home/bin/java'' finished with non-zero exit value 255
```

This fails (without details) on [JooqTask#executeJooq](https://github.com/etiennestuder/gradle-jooq-plugin/blob/524d0317b73d6a6cfaf7b5e1deb8bcb8be8e5b85/src/main/groovy/nu/studer/gradle/jooq/JooqTask.groovy#L93)

**Comment by ben-manes** [comment]
Thanks @amc6! That was indeed the problem. I had forgotten to update the database type (`org.jooq.util.h2.H2Database`). I verified and cannot see any warnings printed with `--debug`, as the error from `javaexec` appears to be suppressed.

**Comment by felipefzdz** [comment]
Hey @ben-manes. Thanks for reporting the issue. It would be definitively great that the plugin would show the error message under that circumstance. I did some test experiments providing a wrong generator name, and I can see the error message. Would it be possible to get a self contained example where we can play around to reproduce the condition?

**Comment by masc3d** [comment]
I would see it as a generic / separate issue. 

It also has other downsides, as `javaexec` also makes it harder to inject custom classes eg. generator strategies, so I wonder if it's really necessary.

**Comment by etiennestuder** [comment]
A custom generator class needs to be on the classpath when executing the jooq code generator. In Gradle, this is configured by adding the dependency to a configuration, regardless of how the jooq code generator is executed. Thus, I don't see how using javaexec is relevant in this context.

https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_custom_generator/build.gradle

**Comment by masc3d** [comment]
> Thus, I don't see how using javaexec is relevant in this context.

because not using `javaexec` would resolve the opaque error issue above immediately. but you're right it's not relevant in the context of this issue.

**Comment by masc3d** [comment]
it's very easy to replicate. eg
```  
...      
        generator {
            database {
                name = 'invalid-class-here'
...
```

**Comment by lukaseder** [comment]
@masc3d Notice though that there is no jOOQ 3.11 (and package rename) specific error message unless the class is prefixed `org.jooq.util`

**Comment by javaHelper** [comment]
Could you please guide me here: https://stackoverflow.com/questions/59444988/caused-by-java-lang-classnotfoundexception-org-jooq-util-jaxb-tools-xmlappenda ?
